services:

    gunicorn:
        build: ./
        ports:
            - "8000:8000"
        volumes:
            - ./cybermillionaire:/cybermillionaire
        networks:
            - nginx_network
            - db_network
        depends_on:
            db:
                condition: service_healthy
        env_file: ../api_config.env

    nginx:
        build: ./nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./cybermillionaire/static:/static
        depends_on:
            - gunicorn
        networks:
            - nginx_network
            
      
    db:
        build: ./mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            timeout: 5s
            retries: 30
            start_period: 30s
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ./cybermillionaire:/cybermillionaire
            - mariadb_data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE: Millionaire
        networks:
            - db_network
        
   
networks:
    nginx_network:
        driver: bridge
    db_network:
        driver: bridge

volumes:
    mariadb_data:
